argo-rollouts:
  fullnameOverride: argorollout
  apiVersionOverrides:
    ingress: networking.k8s.io/v1
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    containerPorts:
      metrics: 8090
      healthz: 8080
  dashboard:
    enabled: true
  ingress:
      # -- Enable dashboard ingress support
      enabled: true
      # -- Dashboard ingress annotations
      annotations: {}
      # -- Dashboard ingress labels
      labels: {}
      # -- Dashboard ingress class name
      ingressClassName: "traefik"

      # -- Dashboard ingress hosts
      ## Argo Rollouts Dashboard Ingress.
      ## Hostnames must be provided if Ingress is enabled.
      ## Secrets must be manually created in the namespace
      hosts: 
        - rudgh21.com

      # -- Dashboard ingress paths
      paths:
        - /
      # -- Dashboard ingress path type
      pathType: Prefix
      # -- Dashboard ingress extra paths
      extraPaths: []
        - path: /*
          pathType: Prefix
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation

      # -- Dashboard ingress tls
      tls: []
